# Generated by Django 6.0.5 on 2026-05-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runrecord',
            name='raw_output',
            field=models.TextField(blank=True),
        ),
    ]
