# Generated by Django 6.0.5 on 2026-05-07 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0002_runrecord_raw_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_json', models.TextField(blank=True)),
                ('docx_path', models.CharField(blank=True, max_length=500)),
                ('raw_output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='pipeline.runrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
